---
# Note: you should protect secrets (passwords, keys, tokens)! Ansible offers a variety of secret providers, e.g. Vault:
# https://docs.ansible.com/ansible/latest/user_guide/vault.html

neos:
  domain: vpro0000.proserver.punkt.de

dehydrated:
  # Dehydrated will generate X.509 certificates through Let's Encrypt.
  # To make this work you'll need to provide a valid domain and update the DNS to point to the corresponding proServer.
  # The certificate will automatically be issued and updated, you only need to use it in your nginx configuration
  # (see roles/neos/templates/nginx/http.d/neos.conf.j2 for example).
  domains: []
    #Common_Name: ['Subject', 'Alternative', 'Names']
    #vpro0000.proserver.punkt.de: []

nginx:
  moved_permanently: []
    #http://vpro0000.proserver.punkt.de: https://vpro0000.proserver.punkt.de

mariadb:
  databases:
    neos:
      name: neos-prd
  users:
    neos:
      username: neos-prd
      password: neos-prd
      hosts:
        neos: localhost
      privileges:
        neos: "neos-prd.*:all"

postgresql:
  databases:
    neos:
      name: neos-prd
      owner: ~neos
  users:
    neos:
      username: neos-prd
      password: neos-prd

elasticsearch:
  elasticsearch.yml:
    cluster:
      name: proserver-neos-prd

mail:
  aliases:
    # Emails with info about system status, security checks and cron issues will go to theses addresses.
    root: noreply@example.com
    proserver: noreply@example.com
    "{{ ansible_hostname }}": noreply@example.com
