---
collections:
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/ansible-collections/community.crypto
    type: git
  - name: https://github.com/ansible-collections/ansible.posix
    type: git

roles:
  - name: apache
    src: https://github.com/punktDe/ansible-proserver-apache
    version: "1.0"
  - name: dehydrated
    src: https://github.com/punktDe/ansible-proserver-dehydrated
    version: "1.0.1"
  - name: elasticsearch
    src: https://github.com/punktDe/ansible-proserver-elasticsearch
  - name: mail
    src: https://github.com/punktDe/ansible-proserver-mail
  - name: mailhog
    src: https://github.com/punktDe/ansible-proserver-mailhog
  - name: mariadb
    src: https://github.com/punktDe/ansible-proserver-mariadb
  - name: nginx
    src: https://github.com/punktDe/ansible-proserver-nginx
    version: "1.0.1"
  - name: oauth2_proxy
    src: https://github.com/punktDe/ansible-proserver-oauth2-proxy
    version: "1.0.1"
  - name: php
    src: https://github.com/punktDe/ansible-proserver-php
    version: "1.0.1"
  - name: postgresql
    src: https://github.com/punktDe/ansible-proserver-postgresql
    version: "1.0.1"
  - name: redis
    src: https://github.com/punktDe/ansible-proserver-redis
  - name: solr
    src: https://github.com/punktDe/ansible-proserver-solr
    version: "1.1.0"
  - name: supervisord
    src: https://github.com/punktDe/ansible-proserver-supervisord
  - name: system
    src: https://github.com/punktDe/ansible-proserver-system
    version: "1.4.1"
