---
# Note: you should protect secrets (passwords, keys, tokens)! Ansible offers a variety of secret providers, e.g. Vault:
# https://docs.ansible.com/ansible/latest/user_guide/vault.html

typo3:
  domain: vpro0000.proserver.punkt.de
  context: Production

dehydrated:
  # Dehydrated will generate X.509 certificates through Let's Encrypt.
  # To make this work you'll need to provide a valid domain and update the DNS to point to the corresponding proServer.
  # The certificate will automatically be issued and updated, you only need to use it in your nginx configuration
  # (see roles/typo3/templates/nginx/http.d/typo3.conf.j2 for example).
  domains:
    #Common_Name: ['Subject', 'Alternative', 'Names']
    vpro0000.proserver.punkt.de: []

nginx:
  moved_permanently:
    http://vpro0000.proserver.punkt.de: https://vpro0000.proserver.punkt.de

mariadb:
  databases:
    typo3:
      name: typo3-prd
  users:
    typo3:
      username: typo3-prd
      password: typo3-prd
      hosts:
        typo3: localhost
      privileges:
        typo3: "typo3-prd.*:all"

postgresql:
  databases:
    typo3:
      name: typo3-prd
      owner: ~typo3
  users:
    typo3:
      username: typo3-prd
      password: typo3-prd

elasticsearch:
  elasticsearch.yml:
    cluster:
      name: proserver-typo3-prd

mail:
  aliases:
    # Emails with info about system status, security checks and cron issues will go to theses addresses.
    root: noreply@example.com
    proserver: noreply@example.com
    "{{ ansible_hostname }}": noreply@example.com
