---
- import_tasks: apache.yaml
  when: groups.apache is defined and inventory_hostname in groups.apache

- import_tasks: nginx.yaml
  when: groups.apache is not defined or inventory_hostname not in groups.apache

- import_tasks: typo3.yaml
