---
dependencies:
  - role: dehydrated
  - role: nginx
    when: groups.apache is not defined or inventory_hostname not in groups.apache
  - role: apache
    when: groups.apache is defined and inventory_hostname in groups.apache
  - role: oauth2_proxy
    when: typo3.oauth2_proxy
  - role: php
