---
- name: Template nginx configuration
  template: src="{{ item }}" dest="{{ render_path }}"
  loop_control:
    label: "{{ render_path }}"
  vars:
    template_dir: "{{ role_path }}/templates/nginx"
    render_path: "{{ nginx.prefix.config }}/{{ item|strip_prefix(template_dir + '/')|strip_suffix('.j2') }}"
  with_fileglob:
    - "{{ template_dir }}/*.j2"
    - "{{ template_dir }}/http.d/*.j2"
  notify: Restart nginx
