---
environment_name: development

neos:
  prefix:
    # Override path to latest release, as we don't have multiple releases in the local dev environment
    # (see roles/neos/defaults/main.yaml for production values).
    current_release: /var/www/neos
  domain: neos.proserver-dev.local
  default_context: Development

typo3:
  prefix:
    current_release: /var/www/typo3
  domain: typo3.proserver-dev.local
  context: Development

nginx:
  # The amount of bits used by default (4096) takes a very long time to generate (happens during the initial
  # provisioning process), which is why we decrease the amount of dhparam bits in development mode.
  dhparam_bits: 1024

php:
  xdebug:
    # Xdebug slows down PHP dramatically, which is why we want to disable it by default.
    # You can toggle Xdebug by executing the "xdebug" command in the proServer virtual machine.
    # Xdebug is only available in the developer box version of a proServer, it is not installed in real proServer environment.
    disable_by_default: yes

mail:
  # We don't want emails to leave our development instance.
  enable_mta: no

mailhog:
  # We want to send emails to MailHog (configure your application to send emails to 127.0.0.1:1025).
  # The MailHog webinterface will be reachable via this domain:
  domain: mailhog.proserver-dev.local

mariadb:
  databases:
    neos:
      name: neos-dev
    typo3:
      name: typo3-dev
  users:
    neos:
      username: neos-dev
      password: neos-dev
      hosts:
        neos: localhost
      privileges:
        neos: "neos-dev.*:all"
    typo3:
      username: typo3-dev
      password: typo3-dev
      hosts:
        typo3: localhost
      privileges:
        typo3: "typo3-dev.*:all"

# postgresql:
#  # The dictionary keys ("neos") will not be used by the role (except for the owner field, read the comment below).
#  # This way you can use Ansible's variable precedence to define a default and override it if needed. For example,
#  # you could define a default database name and password for your app in group vars and override it in host vars.
#  databases:
#    neos:
#      name: neos-dev
#      # "~neos" will be translated to "neos-dev" because postgresql.users.neos.username is "neos-dev".
#      owner: ~neos
#  users:
#    neos:
#      username: neos-dev
#      password: neos-dev
#    typo3:
#      username: typo3-dev
#      password: typo3-dev

elasticsearch:
  elasticsearch.yml:
    # The Elasticsearch role comes with a working set of defaults, see roles/elasticsearch/defaults/main.yaml.
    # You can add or override any elasticsearch.yml option here.
    cluster:
      name: proserver-demo-dev

oauth2_proxy:
  config:
    # Here we could configure access control for MailHog but since this is a local virtual machine we just disable it.
    mailhog: ~
